package loops;

import javax.swing.*;

public class game_loop_2_P1 {

    public game_loop_2_P1(int pos,JLabel P1C1,JLabel P1C2,JLabel P1C3,JLabel P1C4,JLabel P1C5,JLabel P1C6,JLabel P1C7,JLabel P1C8,JLabel P1C9,JLabel P1C10,JLabel P1C11,JLabel P1C12,JLabel P1C13,JLabel P1C14,JLabel P1C15) {
        Icon Imagenes = new ImageIcon(getClass().getResource("/imagenfondo/label.jpg"));
        Icon Imagines1 = new ImageIcon(getClass().getResource("/imagenfondo/personaje_1.png"));
        if (pos == 0) {
            P1C1.setIcon(Imagines1);
            P1C2.setIcon(Imagenes);
            P1C3.setIcon(Imagenes);
            P1C4.setIcon(Imagenes);
            P1C5.setIcon(Imagenes);
            P1C6.setIcon(Imagenes);
            P1C7.setIcon(Imagenes);
            P1C8.setIcon(Imagenes);
            P1C9.setIcon(Imagenes);
            P1C10.setIcon(Imagenes);
            P1C11.setIcon(Imagenes);
            P1C12.setIcon(Imagenes);
            P1C13.setIcon(Imagenes);
            P1C14.setIcon(Imagenes);
            P1C15.setIcon(Imagenes);

        }
        if (pos == 1) {
            P1C1.setIcon(Imagenes);
            P1C2.setIcon(Imagines1);
            P1C3.setIcon(Imagenes);
            P1C4.setIcon(Imagenes);
            P1C5.setIcon(Imagenes);
            P1C6.setIcon(Imagenes);
            P1C7.setIcon(Imagenes);
            P1C8.setIcon(Imagenes);
            P1C9.setIcon(Imagenes);
            P1C9.setIcon(Imagenes);
            P1C10.setIcon(Imagenes);
            P1C11.setIcon(Imagenes);
            P1C12.setIcon(Imagenes);
            P1C13.setIcon(Imagenes);
            P1C14.setIcon(Imagenes);
            P1C15.setIcon(Imagenes);
        }
        if (pos == 2) {
            P1C1.setIcon(Imagenes);
            P1C2.setIcon(Imagenes);
            P1C3.setIcon(Imagines1);
            P1C4.setIcon(Imagenes);
            P1C5.setIcon(Imagenes);
            P1C6.setIcon(Imagenes);
            P1C7.setIcon(Imagenes);
            P1C8.setIcon(Imagenes);
            P1C9.setIcon(Imagenes);
            P1C10.setIcon(Imagenes);
            P1C11.setIcon(Imagenes);
            P1C12.setIcon(Imagenes);
            P1C13.setIcon(Imagenes);
            P1C14.setIcon(Imagenes);
            P1C15.setIcon(Imagenes);
        }
        if (pos == 3) {
            P1C1.setIcon(Imagenes);
            P1C2.setIcon(Imagenes);
            P1C3.setIcon(Imagenes);
            P1C4.setIcon(Imagines1);
            P1C5.setIcon(Imagenes);
            P1C6.setIcon(Imagenes);
            P1C7.setIcon(Imagenes);
            P1C8.setIcon(Imagenes);
            P1C9.setIcon(Imagenes);
            P1C10.setIcon(Imagenes);
            P1C11.setIcon(Imagenes);
            P1C12.setIcon(Imagenes);
            P1C13.setIcon(Imagenes);
            P1C14.setIcon(Imagenes);
            P1C15.setIcon(Imagenes);
        }
        if (pos == 4) {
            P1C1.setIcon(Imagenes);
            P1C2.setIcon(Imagenes);
            P1C3.setIcon(Imagenes);
            P1C4.setIcon(Imagenes);
            P1C5.setIcon(Imagines1);
            P1C6.setIcon(Imagenes);
            P1C7.setIcon(Imagenes);
            P1C8.setIcon(Imagenes);
            P1C9.setIcon(Imagenes);
            P1C10.setIcon(Imagenes);
            P1C11.setIcon(Imagenes);
            P1C12.setIcon(Imagenes);
            P1C13.setIcon(Imagenes);
            P1C14.setIcon(Imagenes);
            P1C15.setIcon(Imagenes);
        }
        if (pos == 5) {
            P1C1.setIcon(Imagenes);
            P1C2.setIcon(Imagenes);
            P1C3.setIcon(Imagenes);
            P1C4.setIcon(Imagenes);
            P1C5.setIcon(Imagenes);
            P1C6.setIcon(Imagines1);
            P1C7.setIcon(Imagenes);
            P1C8.setIcon(Imagenes);
            P1C9.setIcon(Imagenes);
            P1C10.setIcon(Imagenes);
            P1C11.setIcon(Imagenes);
            P1C12.setIcon(Imagenes);
            P1C13.setIcon(Imagenes);
            P1C14.setIcon(Imagenes);
            P1C15.setIcon(Imagenes);
        }
        if (pos == 6) {
            P1C1.setIcon(Imagenes);
            P1C2.setIcon(Imagenes);
            P1C3.setIcon(Imagenes);
            P1C4.setIcon(Imagenes);
            P1C5.setIcon(Imagenes);
            P1C6.setIcon(Imagenes);
            P1C7.setIcon(Imagines1);
            P1C8.setIcon(Imagenes);
            P1C9.setIcon(Imagenes);
            P1C10.setIcon(Imagenes);
            P1C11.setIcon(Imagenes);
            P1C12.setIcon(Imagenes);
            P1C13.setIcon(Imagenes);
            P1C14.setIcon(Imagenes);
            P1C15.setIcon(Imagenes);
        }
        if (pos == 7) {
            P1C1.setIcon(Imagenes);
            P1C2.setIcon(Imagenes);
            P1C3.setIcon(Imagenes);
            P1C4.setIcon(Imagenes);
            P1C5.setIcon(Imagenes);
            P1C6.setIcon(Imagenes);
            P1C7.setIcon(Imagenes);
            P1C8.setIcon(Imagines1);
            P1C9.setIcon(Imagenes);
            P1C10.setIcon(Imagenes);
            P1C11.setIcon(Imagenes);
            P1C12.setIcon(Imagenes);
            P1C13.setIcon(Imagenes);
            P1C14.setIcon(Imagenes);
            P1C15.setIcon(Imagenes);
        }
        if (pos == 8) {
            P1C1.setIcon(Imagenes);
            P1C2.setIcon(Imagenes);
            P1C3.setIcon(Imagenes);
            P1C4.setIcon(Imagenes);
            P1C5.setIcon(Imagenes);
            P1C6.setIcon(Imagenes);
            P1C7.setIcon(Imagenes);
            P1C8.setIcon(Imagenes);
            P1C9.setIcon(Imagines1);
            P1C10.setIcon(Imagenes);
            P1C11.setIcon(Imagenes);
            P1C12.setIcon(Imagenes);
            P1C13.setIcon(Imagenes);
            P1C14.setIcon(Imagenes);
            P1C15.setIcon(Imagenes);
        }
        if (pos == 9) {
            P1C1.setIcon(Imagenes);
            P1C2.setIcon(Imagenes);
            P1C3.setIcon(Imagenes);
            P1C4.setIcon(Imagenes);
            P1C5.setIcon(Imagenes);
            P1C6.setIcon(Imagenes);
            P1C7.setIcon(Imagenes);
            P1C8.setIcon(Imagenes);
            P1C9.setIcon(Imagines1);
            P1C10.setIcon(Imagenes);
            P1C11.setIcon(Imagenes);
            P1C12.setIcon(Imagenes);
            P1C13.setIcon(Imagenes);
            P1C14.setIcon(Imagenes);
            P1C15.setIcon(Imagenes);
        }
        if (pos == 10) {
            P1C1.setIcon(Imagenes);
            P1C2.setIcon(Imagenes);
            P1C3.setIcon(Imagenes);
            P1C4.setIcon(Imagenes);
            P1C5.setIcon(Imagenes);
            P1C6.setIcon(Imagenes);
            P1C7.setIcon(Imagenes);
            P1C8.setIcon(Imagenes);
            P1C9.setIcon(Imagenes);
            P1C10.setIcon(Imagines1);
            P1C11.setIcon(Imagenes);
            P1C12.setIcon(Imagenes);
            P1C13.setIcon(Imagenes);
            P1C14.setIcon(Imagenes);
            P1C15.setIcon(Imagenes);
        }
        if (pos == 11) {
            P1C1.setIcon(Imagenes);
            P1C2.setIcon(Imagenes);
            P1C3.setIcon(Imagenes);
            P1C4.setIcon(Imagenes);
            P1C5.setIcon(Imagenes);
            P1C6.setIcon(Imagenes);
            P1C7.setIcon(Imagenes);
            P1C8.setIcon(Imagenes);
            P1C9.setIcon(Imagenes);
            P1C10.setIcon(Imagenes);
            P1C11.setIcon(Imagines1);
            P1C12.setIcon(Imagenes);
            P1C13.setIcon(Imagenes);
            P1C14.setIcon(Imagenes);
            P1C15.setIcon(Imagenes);
        }
        if (pos == 12) {
            P1C1.setIcon(Imagenes);
            P1C2.setIcon(Imagenes);
            P1C3.setIcon(Imagenes);
            P1C4.setIcon(Imagenes);
            P1C5.setIcon(Imagenes);
            P1C6.setIcon(Imagenes);
            P1C7.setIcon(Imagenes);
            P1C8.setIcon(Imagenes);
            P1C9.setIcon(Imagenes);
            P1C10.setIcon(Imagenes);
            P1C11.setIcon(Imagenes);
            P1C12.setIcon(Imagines1);
            P1C13.setIcon(Imagenes);
            P1C14.setIcon(Imagenes);
            P1C15.setIcon(Imagenes);
        }
        if (pos == 13) {
            P1C1.setIcon(Imagenes);
            P1C2.setIcon(Imagenes);
            P1C3.setIcon(Imagenes);
            P1C4.setIcon(Imagenes);
            P1C5.setIcon(Imagenes);
            P1C6.setIcon(Imagenes);
            P1C7.setIcon(Imagenes);
            P1C8.setIcon(Imagenes);
            P1C9.setIcon(Imagenes);
            P1C10.setIcon(Imagenes);
            P1C11.setIcon(Imagenes);
            P1C12.setIcon(Imagenes);
            P1C13.setIcon(Imagines1);
            P1C14.setIcon(Imagenes);
            P1C15.setIcon(Imagenes);
        }
        if (pos == 14) {
            P1C1.setIcon(Imagenes);
            P1C2.setIcon(Imagenes);
            P1C3.setIcon(Imagenes);
            P1C4.setIcon(Imagenes);
            P1C5.setIcon(Imagenes);
            P1C6.setIcon(Imagenes);
            P1C7.setIcon(Imagenes);
            P1C8.setIcon(Imagenes);
            P1C9.setIcon(Imagenes);
            P1C10.setIcon(Imagenes);
            P1C11.setIcon(Imagenes);
            P1C12.setIcon(Imagenes);
            P1C13.setIcon(Imagenes);
            P1C14.setIcon(Imagines1);
            P1C15.setIcon(Imagenes);
        }
        if (pos == 15) {
            P1C1.setIcon(Imagenes);
            P1C2.setIcon(Imagenes);
            P1C3.setIcon(Imagenes);
            P1C4.setIcon(Imagenes);
            P1C5.setIcon(Imagenes);
            P1C6.setIcon(Imagenes);
            P1C7.setIcon(Imagenes);
            P1C8.setIcon(Imagenes);
            P1C9.setIcon(Imagenes);
            P1C10.setIcon(Imagenes);
            P1C11.setIcon(Imagenes);
            P1C12.setIcon(Imagenes);
            P1C13.setIcon(Imagenes);
            P1C14.setIcon(Imagenes);
            P1C15.setIcon(Imagines1);

        }
    }
}
