package loops;

import javax.swing.*;

public class game_loop_3_P2 {
    public game_loop_3_P2(int pos,JLabel P2C1,JLabel P2C2,JLabel P2C3,JLabel P2C4,JLabel P2C5,JLabel P2C6,JLabel P2C7,JLabel P2C8,JLabel P2C9,JLabel P2C10,JLabel P2C11,JLabel P2C12,JLabel P2C13,JLabel P2C14,JLabel P2C15,JLabel P2C16,JLabel P2C17,JLabel P2C18,JLabel P2C19,JLabel P2C20, JLabel P2C21,JLabel P2C22,JLabel P2C23,JLabel P2C24,JLabel P2C25) {
        Icon fondo = new ImageIcon(getClass().getResource("/imagenfondo/label.jpg"));
        Icon Imagenes2 = new ImageIcon(getClass().getResource("/imagenfondo/personaje_2.png"));
        if (pos == 0) {
            P2C1.setIcon(Imagenes2);
            P2C2.setIcon(fondo);
            P2C3.setIcon(fondo);
            P2C4.setIcon(fondo);
            P2C5.setIcon(fondo);
            P2C6.setIcon(fondo);
            P2C7.setIcon(fondo);
            P2C8.setIcon(fondo);
            P2C9.setIcon(fondo);
            P2C10.setIcon(fondo);
            P2C11.setIcon(fondo);
            P2C12.setIcon(fondo);
            P2C13.setIcon(fondo);
            P2C14.setIcon(fondo);
            P2C15.setIcon(fondo);
            P2C16.setIcon(fondo);
            P2C17.setIcon(fondo);
            P2C18.setIcon(fondo);
            P2C19.setIcon(fondo);
            P2C20.setIcon(fondo);
            P2C21.setIcon(fondo);
            P2C22.setIcon(fondo);
            P2C23.setIcon(fondo);
            P2C24.setIcon(fondo);
            P2C25.setIcon(fondo);

        }
        if (pos == 1) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(Imagenes2);
            P2C3.setIcon(fondo);
            P2C4.setIcon(fondo);
            P2C5.setIcon(fondo);
            P2C6.setIcon(fondo);
            P2C7.setIcon(fondo);
            P2C8.setIcon(fondo);
            P2C9.setIcon(fondo);
            P2C10.setIcon(fondo);
            P2C11.setIcon(fondo);
            P2C12.setIcon(fondo);
            P2C13.setIcon(fondo);
            P2C14.setIcon(fondo);
            P2C15.setIcon(fondo);
            P2C16.setIcon(fondo);
            P2C17.setIcon(fondo);
            P2C18.setIcon(fondo);
            P2C19.setIcon(fondo);
            P2C20.setIcon(fondo);
            P2C21.setIcon(fondo);
            P2C22.setIcon(fondo);
            P2C23.setIcon(fondo);
            P2C24.setIcon(fondo);
            P2C25.setIcon(fondo);

        }
        if (pos == 2) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(fondo);
            P2C3.setIcon(Imagenes2);
            P2C4.setIcon(fondo);
            P2C5.setIcon(fondo);
            P2C6.setIcon(fondo);
            P2C7.setIcon(fondo);
            P2C8.setIcon(fondo);
            P2C9.setIcon(fondo);
            P2C10.setIcon(fondo);
            P2C11.setIcon(fondo);
            P2C12.setIcon(fondo);
            P2C13.setIcon(fondo);
            P2C14.setIcon(fondo);
            P2C15.setIcon(fondo);
            P2C16.setIcon(fondo);
            P2C17.setIcon(fondo);
            P2C18.setIcon(fondo);
            P2C19.setIcon(fondo);
            P2C20.setIcon(fondo);
            P2C21.setIcon(fondo);
            P2C22.setIcon(fondo);
            P2C23.setIcon(fondo);
            P2C24.setIcon(fondo);
            P2C25.setIcon(fondo);
        }
        if (pos == 3) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(fondo);
            P2C3.setIcon(fondo);
            P2C4.setIcon(Imagenes2);
            P2C5.setIcon(fondo);
            P2C6.setIcon(fondo);
            P2C7.setIcon(fondo);
            P2C8.setIcon(fondo);
            P2C9.setIcon(fondo);
            P2C10.setIcon(fondo);
            P2C11.setIcon(fondo);
            P2C12.setIcon(fondo);
            P2C13.setIcon(fondo);
            P2C14.setIcon(fondo);
            P2C15.setIcon(fondo);
            P2C16.setIcon(fondo);
            P2C17.setIcon(fondo);
            P2C18.setIcon(fondo);
            P2C19.setIcon(fondo);
            P2C20.setIcon(fondo);
            P2C21.setIcon(fondo);
            P2C22.setIcon(fondo);
            P2C23.setIcon(fondo);
            P2C24.setIcon(fondo);
            P2C25.setIcon(fondo);

        }
        if (pos == 4) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(fondo);
            P2C3.setIcon(fondo);
            P2C4.setIcon(fondo);
            P2C5.setIcon(Imagenes2);
            P2C6.setIcon(fondo);
            P2C7.setIcon(fondo);
            P2C8.setIcon(fondo);
            P2C9.setIcon(fondo);
            P2C10.setIcon(fondo);
            P2C11.setIcon(fondo);
            P2C12.setIcon(fondo);
            P2C13.setIcon(fondo);
            P2C14.setIcon(fondo);
            P2C15.setIcon(fondo);
            P2C16.setIcon(fondo);
            P2C17.setIcon(fondo);
            P2C18.setIcon(fondo);
            P2C19.setIcon(fondo);
            P2C20.setIcon(fondo);
            P2C21.setIcon(fondo);
            P2C22.setIcon(fondo);
            P2C23.setIcon(fondo);
            P2C24.setIcon(fondo);
            P2C25.setIcon(fondo);

        }
        if (pos == 5) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(fondo);
            P2C3.setIcon(fondo);
            P2C4.setIcon(fondo);
            P2C5.setIcon(fondo);
            P2C6.setIcon(Imagenes2);
            P2C7.setIcon(fondo);
            P2C8.setIcon(fondo);
            P2C9.setIcon(fondo);
            P2C10.setIcon(fondo);
            P2C11.setIcon(fondo);
            P2C12.setIcon(fondo);
            P2C13.setIcon(fondo);
            P2C14.setIcon(fondo);
            P2C15.setIcon(fondo);
            P2C16.setIcon(fondo);
            P2C17.setIcon(fondo);
            P2C18.setIcon(fondo);
            P2C19.setIcon(fondo);
            P2C20.setIcon(fondo);
            P2C21.setIcon(fondo);
            P2C22.setIcon(fondo);
            P2C23.setIcon(fondo);
            P2C24.setIcon(fondo);
            P2C25.setIcon(fondo);

        }
        if (pos == 6) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(fondo);
            P2C3.setIcon(fondo);
            P2C4.setIcon(fondo);
            P2C5.setIcon(fondo);
            P2C6.setIcon(fondo);
            P2C7.setIcon(Imagenes2);
            P2C8.setIcon(fondo);
            P2C9.setIcon(fondo);
            P2C10.setIcon(fondo);
            P2C11.setIcon(fondo);
            P2C12.setIcon(fondo);
            P2C13.setIcon(fondo);
            P2C14.setIcon(fondo);
            P2C15.setIcon(fondo);
            P2C16.setIcon(fondo);
            P2C17.setIcon(fondo);
            P2C18.setIcon(fondo);
            P2C19.setIcon(fondo);
            P2C20.setIcon(fondo);
            P2C21.setIcon(fondo);
            P2C22.setIcon(fondo);
            P2C23.setIcon(fondo);
            P2C24.setIcon(fondo);
            P2C25.setIcon(fondo);

        }
        if (pos == 7) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(fondo);
            P2C3.setIcon(fondo);
            P2C4.setIcon(fondo);
            P2C5.setIcon(fondo);
            P2C6.setIcon(fondo);
            P2C7.setIcon(fondo);
            P2C8.setIcon(Imagenes2);
            P2C9.setIcon(fondo);
            P2C10.setIcon(fondo);
            P2C11.setIcon(fondo);
            P2C12.setIcon(fondo);
            P2C13.setIcon(fondo);
            P2C14.setIcon(fondo);
            P2C15.setIcon(fondo);
            P2C16.setIcon(fondo);
            P2C17.setIcon(fondo);
            P2C18.setIcon(fondo);
            P2C19.setIcon(fondo);
            P2C20.setIcon(fondo);
            P2C21.setIcon(fondo);
            P2C22.setIcon(fondo);
            P2C23.setIcon(fondo);
            P2C24.setIcon(fondo);
            P2C25.setIcon(fondo);

        }
        if (pos == 8) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(fondo);
            P2C3.setIcon(fondo);
            P2C4.setIcon(fondo);
            P2C5.setIcon(fondo);
            P2C6.setIcon(fondo);
            P2C7.setIcon(fondo);
            P2C8.setIcon(fondo);
            P2C9.setIcon(Imagenes2);
            P2C10.setIcon(fondo);
            P2C11.setIcon(fondo);
            P2C12.setIcon(fondo);
            P2C13.setIcon(fondo);
            P2C14.setIcon(fondo);
            P2C15.setIcon(fondo);
            P2C16.setIcon(fondo);
            P2C17.setIcon(fondo);
            P2C18.setIcon(fondo);
            P2C19.setIcon(fondo);
            P2C20.setIcon(fondo);
            P2C21.setIcon(fondo);
            P2C22.setIcon(fondo);
            P2C23.setIcon(fondo);
            P2C24.setIcon(fondo);
            P2C25.setIcon(fondo);

        }
        if (pos == 9) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(fondo);
            P2C3.setIcon(fondo);
            P2C4.setIcon(fondo);
            P2C5.setIcon(fondo);
            P2C6.setIcon(fondo);
            P2C7.setIcon(fondo);
            P2C8.setIcon(fondo);
            P2C9.setIcon(fondo);
            P2C10.setIcon(Imagenes2);
            P2C11.setIcon(fondo);
            P2C12.setIcon(fondo);
            P2C13.setIcon(fondo);
            P2C14.setIcon(fondo);
            P2C15.setIcon(fondo);
            P2C16.setIcon(fondo);
            P2C17.setIcon(fondo);
            P2C18.setIcon(fondo);
            P2C19.setIcon(fondo);
            P2C20.setIcon(fondo);
            P2C21.setIcon(fondo);
            P2C22.setIcon(fondo);
            P2C23.setIcon(fondo);
            P2C24.setIcon(fondo);
            P2C25.setIcon(fondo);


        }
        if (pos == 10) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(fondo);
            P2C3.setIcon(fondo);
            P2C4.setIcon(fondo);
            P2C5.setIcon(fondo);
            P2C6.setIcon(fondo);
            P2C7.setIcon(fondo);
            P2C8.setIcon(fondo);
            P2C9.setIcon(fondo);
            P2C10.setIcon(fondo);
            P2C11.setIcon(Imagenes2);
            P2C12.setIcon(fondo);
            P2C13.setIcon(fondo);
            P2C14.setIcon(fondo);
            P2C15.setIcon(fondo);
            P2C16.setIcon(fondo);
            P2C17.setIcon(fondo);
            P2C18.setIcon(fondo);
            P2C19.setIcon(fondo);
            P2C20.setIcon(fondo);
            P2C21.setIcon(fondo);
            P2C22.setIcon(fondo);
            P2C23.setIcon(fondo);
            P2C24.setIcon(fondo);
            P2C25.setIcon(fondo);


        }
        if (pos == 11) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(fondo);
            P2C3.setIcon(fondo);
            P2C4.setIcon(fondo);
            P2C5.setIcon(fondo);
            P2C6.setIcon(fondo);
            P2C7.setIcon(fondo);
            P2C8.setIcon(fondo);
            P2C9.setIcon(fondo);
            P2C10.setIcon(fondo);
            P2C11.setIcon(fondo);
            P2C12.setIcon(Imagenes2);
            P2C13.setIcon(fondo);
            P2C14.setIcon(fondo);
            P2C15.setIcon(fondo);
            P2C16.setIcon(fondo);
            P2C17.setIcon(fondo);
            P2C18.setIcon(fondo);
            P2C19.setIcon(fondo);
            P2C20.setIcon(fondo);
            P2C21.setIcon(fondo);
            P2C22.setIcon(fondo);
            P2C23.setIcon(fondo);
            P2C24.setIcon(fondo);
            P2C25.setIcon(fondo);


        }
        if (pos == 12) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(fondo);
            P2C3.setIcon(fondo);
            P2C4.setIcon(fondo);
            P2C5.setIcon(fondo);
            P2C6.setIcon(fondo);
            P2C7.setIcon(fondo);
            P2C8.setIcon(fondo);
            P2C9.setIcon(fondo);
            P2C10.setIcon(fondo);
            P2C11.setIcon(fondo);
            P2C12.setIcon(fondo);
            P2C13.setIcon(Imagenes2);
            P2C14.setIcon(fondo);
            P2C15.setIcon(fondo);
            P2C16.setIcon(fondo);
            P2C17.setIcon(fondo);
            P2C18.setIcon(fondo);
            P2C19.setIcon(fondo);
            P2C20.setIcon(fondo);
            P2C21.setIcon(fondo);
            P2C22.setIcon(fondo);
            P2C23.setIcon(fondo);
            P2C24.setIcon(fondo);
            P2C25.setIcon(fondo);


        }
        if (pos == 13) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(fondo);
            P2C3.setIcon(fondo);
            P2C4.setIcon(fondo);
            P2C5.setIcon(fondo);
            P2C6.setIcon(fondo);
            P2C7.setIcon(fondo);
            P2C8.setIcon(fondo);
            P2C9.setIcon(fondo);
            P2C10.setIcon(fondo);
            P2C11.setIcon(fondo);
            P2C12.setIcon(fondo);
            P2C13.setIcon(fondo);
            P2C14.setIcon(Imagenes2);
            P2C15.setIcon(fondo);
            P2C16.setIcon(fondo);
            P2C17.setIcon(fondo);
            P2C18.setIcon(fondo);
            P2C19.setIcon(fondo);
            P2C20.setIcon(fondo);
            P2C21.setIcon(fondo);
            P2C22.setIcon(fondo);
            P2C23.setIcon(fondo);
            P2C24.setIcon(fondo);
            P2C25.setIcon(fondo);


        }
        if (pos == 14) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(fondo);
            P2C3.setIcon(fondo);
            P2C4.setIcon(fondo);
            P2C5.setIcon(fondo);
            P2C6.setIcon(fondo);
            P2C7.setIcon(fondo);
            P2C8.setIcon(fondo);
            P2C9.setIcon(fondo);
            P2C10.setIcon(fondo);
            P2C11.setIcon(fondo);
            P2C12.setIcon(fondo);
            P2C13.setIcon(fondo);
            P2C14.setIcon(fondo);
            P2C15.setIcon(Imagenes2);
            P2C16.setIcon(fondo);
            P2C17.setIcon(fondo);
            P2C18.setIcon(fondo);
            P2C19.setIcon(fondo);
            P2C20.setIcon(fondo);
            P2C21.setIcon(fondo);
            P2C22.setIcon(fondo);
            P2C23.setIcon(fondo);
            P2C24.setIcon(fondo);
            P2C25.setIcon(fondo);


        }
        if (pos == 15) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(fondo);
            P2C3.setIcon(fondo);
            P2C4.setIcon(fondo);
            P2C5.setIcon(fondo);
            P2C6.setIcon(fondo);
            P2C7.setIcon(fondo);
            P2C8.setIcon(fondo);
            P2C9.setIcon(fondo);
            P2C10.setIcon(fondo);
            P2C11.setIcon(fondo);
            P2C12.setIcon(fondo);
            P2C13.setIcon(fondo);
            P2C14.setIcon(fondo);
            P2C15.setIcon(fondo);
            P2C16.setIcon(Imagenes2);
            P2C17.setIcon(fondo);
            P2C18.setIcon(fondo);
            P2C19.setIcon(fondo);
            P2C20.setIcon(fondo);
            P2C21.setIcon(fondo);
            P2C22.setIcon(fondo);
            P2C23.setIcon(fondo);
            P2C24.setIcon(fondo);
            P2C25.setIcon(fondo);


        }
        if (pos == 16) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(fondo);
            P2C3.setIcon(fondo);
            P2C4.setIcon(fondo);
            P2C5.setIcon(fondo);
            P2C6.setIcon(fondo);
            P2C7.setIcon(fondo);
            P2C8.setIcon(fondo);
            P2C9.setIcon(fondo);
            P2C10.setIcon(fondo);
            P2C11.setIcon(fondo);
            P2C12.setIcon(fondo);
            P2C13.setIcon(fondo);
            P2C14.setIcon(fondo);
            P2C15.setIcon(fondo);
            P2C16.setIcon(fondo);
            P2C17.setIcon(Imagenes2);
            P2C18.setIcon(fondo);
            P2C19.setIcon(fondo);
            P2C20.setIcon(fondo);
            P2C21.setIcon(fondo);
            P2C22.setIcon(fondo);
            P2C23.setIcon(fondo);
            P2C24.setIcon(fondo);
            P2C25.setIcon(fondo);


        }
        if (pos == 17) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(fondo);
            P2C3.setIcon(fondo);
            P2C4.setIcon(fondo);
            P2C5.setIcon(fondo);
            P2C6.setIcon(fondo);
            P2C7.setIcon(fondo);
            P2C8.setIcon(fondo);
            P2C9.setIcon(fondo);
            P2C10.setIcon(fondo);
            P2C11.setIcon(fondo);
            P2C12.setIcon(fondo);
            P2C13.setIcon(fondo);
            P2C14.setIcon(fondo);
            P2C15.setIcon(fondo);
            P2C16.setIcon(fondo);
            P2C17.setIcon(fondo);
            P2C18.setIcon(Imagenes2);
            P2C19.setIcon(fondo);
            P2C20.setIcon(fondo);
            P2C21.setIcon(fondo);
            P2C22.setIcon(fondo);
            P2C23.setIcon(fondo);
            P2C24.setIcon(fondo);
            P2C25.setIcon(fondo);


        }
        if (pos == 18) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(fondo);
            P2C3.setIcon(fondo);
            P2C4.setIcon(fondo);
            P2C5.setIcon(fondo);
            P2C6.setIcon(fondo);
            P2C7.setIcon(fondo);
            P2C8.setIcon(fondo);
            P2C9.setIcon(fondo);
            P2C10.setIcon(fondo);
            P2C11.setIcon(fondo);
            P2C12.setIcon(fondo);
            P2C13.setIcon(fondo);
            P2C14.setIcon(fondo);
            P2C15.setIcon(fondo);
            P2C16.setIcon(fondo);
            P2C17.setIcon(fondo);
            P2C18.setIcon(fondo);
            P2C19.setIcon(Imagenes2);
            P2C20.setIcon(fondo);
            P2C21.setIcon(fondo);
            P2C22.setIcon(fondo);
            P2C23.setIcon(fondo);
            P2C24.setIcon(fondo);
            P2C25.setIcon(fondo);


        }
        if (pos == 19) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(fondo);
            P2C3.setIcon(fondo);
            P2C4.setIcon(fondo);
            P2C5.setIcon(fondo);
            P2C6.setIcon(fondo);
            P2C7.setIcon(fondo);
            P2C8.setIcon(fondo);
            P2C9.setIcon(fondo);
            P2C10.setIcon(fondo);
            P2C11.setIcon(fondo);
            P2C12.setIcon(fondo);
            P2C13.setIcon(fondo);
            P2C14.setIcon(fondo);
            P2C15.setIcon(fondo);
            P2C16.setIcon(fondo);
            P2C17.setIcon(fondo);
            P2C18.setIcon(fondo);
            P2C19.setIcon(fondo);
            P2C20.setIcon(Imagenes2);
            P2C21.setIcon(fondo);
            P2C22.setIcon(fondo);
            P2C23.setIcon(fondo);
            P2C24.setIcon(fondo);
            P2C25.setIcon(fondo);


        }
        if (pos == 20) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(fondo);
            P2C3.setIcon(fondo);
            P2C4.setIcon(fondo);
            P2C5.setIcon(fondo);
            P2C6.setIcon(fondo);
            P2C7.setIcon(fondo);
            P2C8.setIcon(fondo);
            P2C9.setIcon(fondo);
            P2C10.setIcon(fondo);
            P2C11.setIcon(fondo);
            P2C12.setIcon(fondo);
            P2C13.setIcon(fondo);
            P2C14.setIcon(fondo);
            P2C15.setIcon(fondo);
            P2C16.setIcon(fondo);
            P2C17.setIcon(fondo);
            P2C18.setIcon(fondo);
            P2C19.setIcon(fondo);
            P2C20.setIcon(fondo);
            P2C21.setIcon(Imagenes2);
            P2C22.setIcon(fondo);
            P2C23.setIcon(fondo);
            P2C24.setIcon(fondo);
            P2C25.setIcon(fondo);


        }
        if (pos == 21) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(fondo);
            P2C3.setIcon(fondo);
            P2C4.setIcon(fondo);
            P2C5.setIcon(fondo);
            P2C6.setIcon(fondo);
            P2C7.setIcon(fondo);
            P2C8.setIcon(fondo);
            P2C9.setIcon(fondo);
            P2C10.setIcon(fondo);
            P2C11.setIcon(fondo);
            P2C12.setIcon(fondo);
            P2C13.setIcon(fondo);
            P2C14.setIcon(fondo);
            P2C15.setIcon(fondo);
            P2C16.setIcon(fondo);
            P2C17.setIcon(fondo);
            P2C18.setIcon(fondo);
            P2C19.setIcon(fondo);
            P2C20.setIcon(fondo);
            P2C21.setIcon(fondo);
            P2C22.setIcon(Imagenes2);
            P2C23.setIcon(fondo);
            P2C24.setIcon(fondo);
            P2C25.setIcon(fondo);


        }
        if (pos == 22) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(fondo);
            P2C3.setIcon(fondo);
            P2C4.setIcon(fondo);
            P2C5.setIcon(fondo);
            P2C6.setIcon(fondo);
            P2C7.setIcon(fondo);
            P2C8.setIcon(fondo);
            P2C9.setIcon(fondo);
            P2C10.setIcon(fondo);
            P2C11.setIcon(fondo);
            P2C12.setIcon(fondo);
            P2C13.setIcon(fondo);
            P2C14.setIcon(fondo);
            P2C15.setIcon(fondo);
            P2C16.setIcon(fondo);
            P2C17.setIcon(fondo);
            P2C18.setIcon(fondo);
            P2C19.setIcon(fondo);
            P2C20.setIcon(fondo);
            P2C21.setIcon(fondo);
            P2C22.setIcon(fondo);
            P2C23.setIcon(Imagenes2);
            P2C24.setIcon(fondo);
            P2C25.setIcon(fondo);


        }
        if (pos == 23) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(fondo);
            P2C3.setIcon(fondo);
            P2C4.setIcon(fondo);
            P2C5.setIcon(fondo);
            P2C6.setIcon(fondo);
            P2C7.setIcon(fondo);
            P2C8.setIcon(fondo);
            P2C9.setIcon(fondo);
            P2C10.setIcon(fondo);
            P2C11.setIcon(fondo);
            P2C12.setIcon(fondo);
            P2C13.setIcon(fondo);
            P2C14.setIcon(fondo);
            P2C15.setIcon(fondo);
            P2C16.setIcon(fondo);
            P2C17.setIcon(fondo);
            P2C18.setIcon(fondo);
            P2C19.setIcon(fondo);
            P2C20.setIcon(fondo);
            P2C21.setIcon(fondo);
            P2C22.setIcon(fondo);
            P2C23.setIcon(fondo);
            P2C24.setIcon(Imagenes2);
            P2C25.setIcon(fondo);
        }
        if (pos == 24) {
            P2C1.setIcon(fondo);
            P2C2.setIcon(fondo);
            P2C3.setIcon(fondo);
            P2C4.setIcon(fondo);
            P2C5.setIcon(fondo);
            P2C6.setIcon(fondo);
            P2C7.setIcon(fondo);
            P2C8.setIcon(fondo);
            P2C9.setIcon(fondo);
            P2C10.setIcon(fondo);
            P2C11.setIcon(fondo);
            P2C12.setIcon(fondo);
            P2C13.setIcon(fondo);
            P2C14.setIcon(fondo);
            P2C15.setIcon(fondo);
            P2C16.setIcon(fondo);
            P2C17.setIcon(fondo);
            P2C18.setIcon(fondo);
            P2C19.setIcon(fondo);
            P2C20.setIcon(fondo);
            P2C21.setIcon(fondo);
            P2C22.setIcon(fondo);
            P2C23.setIcon(fondo);
            P2C24.setIcon(fondo);
            P2C25.setIcon(Imagenes2);

        }
    }
}
